### PR TITLE
Allow for custom atom representing None

### PR DESCRIPTION
**Pull request by s2hc-johan**
Different libraries have different atom definitions of
null/None/nil/undefined. This makes the lib transparent and
lets the programmer decide to what atom None should be encoded
to and what atom that should be decoded to None.

I didn't commit the new cython generated cpp files, I can do that if desired.

### CODE REVIEW

**Comment by jhgg** [comment]
Please re-generate the cpp files then 👌 to merge.

**Comment by jhgg** [comment]
Also `erlpack_append_nil` is used in the node module. Put it back

**Comment by s2hc-johan** [comment]
oops missed the node module, sorry. With some hint I could make the same change in node so the packages are consistent. Don't have any good test env. for that though.

**Comment by zorkian** [comment]
This no longer applies. Sorry for the failed review here on our end -- but if you still want this functionality, please update the PR and poke us. `zorkian#0001` or @zorkian and I'll take a look.

**Pull request closed without merging**
